version: '3.9'

services:
  app:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - "./src:/kq_back/src"
      - "./logs:/var/log"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongo
    networks:
      koshqon:

  mongo:
    container_name: mongo
    image: mongo:7.0.8
    restart: unless-stopped
    volumes:
      - "./mongo:/data/db"
    ports:
      - "27017:27017"
    networks:
      koshqon:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      koshqon:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      koshqon:

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data

networks:
  koshqon:
    external: true